name       : haskell-tagsoup
version    : 0.14.6
release    : 3
source     :
    - https://hackage.haskell.org/package/tagsoup-0.14.6/tagsoup-0.14.6.tar.gz : 4b4ed4db1428e859389d628dd5755074f659a424ec49934ec53e44b0fc6a63fb
license    : BSD-3-Clause
component  : programming.haskell
summary    : TagSoup is a library for parsing HTML/XML.
description: |
    TagSoup is a library for parsing HTML/XML.
builddeps  :
    - ghc
    - haskell-cabal-install
    - haskell-text
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
