name       : haskell-tagsoup
version    : 0.14.8
release    : 4
source     :
    - https://hackage.haskell.org/package/tagsoup-0.14.8/tagsoup-0.14.8.tar.gz : ba7e5500d853d29f0675b90655b7fdd032a4a7eee82a56e7ee3ef9949fe93ad5
license    : BSD-3-Clause
component  : programming.haskell
summary    : TagSoup is a library for parsing HTML/XML.
description: |
    TagSoup is a library for parsing HTML/XML.
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
