name       : haskell-tagsoup
version    : 0.14.1
release    : 1
source     :
    - https://hackage.haskell.org/package/tagsoup-0.14.1/tagsoup-0.14.1.tar.gz : 028be660a864e0918f99f90471caea72af2bfbf8a64a423e181b2b29f9c64aeb
license    : BSD-3-Clause
component  : programming.haskell
summary    : TagSoup is a library for parsing HTML/XML.
description: |
    TagSoup is a library for parsing HTML/XML.
builddeps  :
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
